/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database reachability check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and email a verification token
         * @description If the email is already registered, this still returns 201 with a fresh id that resolves to nothing — the response cannot be used to tell whether an email is already taken. See decisions.md.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate an account with a verification token */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and receive an access/refresh token pair */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token for a new access/refresh pair
         * @description Presenting a token that was already rotated or revoked fails this call and revokes every other token descended from the same login. See decisions.md.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the session a refresh token belongs to
         * @description Idempotent — an unknown or already-dead token is not an error.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a password-reset token if the account exists
         * @description Always returns the same response whether or not the email exists — see decisions.md.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password given a valid reset token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-deleted user accounts */
        get: operations["listUsersAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one user account, including a soft-deleted one */
        get: operations["getUserAdmin"];
        put?: never;
        post?: never;
        /**
         * Soft-delete and anonymize a user account
         * @description Anonymizes the row (email rewritten, password invalidated) and revokes every session the user holds. Idempotent — deleting an already-deleted account is still 204. An admin may not delete their own account. See decisions.md.
         */
        delete: operations["deleteUserAdmin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin override for the self-service email-verification gate
         * @description Lets the user use the app immediately, without going through /auth/verify-email. Idempotent. See decisions.md.
         */
        post: operations["activateUserAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a user's role
         * @description An admin may not demote themselves away from admin — see decisions.md.
         */
        patch: operations["changeUserRoleAdmin"];
        trace?: never;
    };
    "/admin/users/{id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email the user a password-reset token
         * @description Reuses the exact same token-issuing flow as the self-service /auth/password/forgot, keyed by id instead of email. No plaintext password ever appears in this request or response — see decisions.md.
         */
        post: operations["triggerPasswordResetAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Block a user account
         * @description Revokes every session the user holds and rejects future logins with `account_blocked`. An admin may not block their own account. See decisions.md.
         */
        post: operations["blockUserAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unblock a user account */
        post: operations["unblockUserAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description Stable machine-readable identifier. Switch on this, never on `message`.
             * @example validation_failed
             */
            code: string;
            /** @description Human-readable, may change without a version bump. */
            message: string;
            /** @description Present even when null. Structured extra context, e.g. field errors. */
            details: {
                [key: string]: unknown;
            } | null;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @enum {string} */
            db: "ok";
        };
        HealthEnvelope: {
            data: components["schemas"]["Health"];
            meta: Record<string, never>;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        RegisteredUser: {
            /**
             * Format: uuid
             * @description UUIDv7. May not correspond to a real account — see decisions.md.
             */
            id: string;
            /** Format: email */
            email: string;
        };
        RegisterEnvelope: {
            data: components["schemas"]["RegisteredUser"];
            meta: Record<string, never>;
        };
        TokenRequest: {
            token: string;
        };
        Verified: {
            /** @enum {boolean} */
            verified: true;
        };
        VerifiedEnvelope: {
            data: components["schemas"]["Verified"];
            meta: Record<string, never>;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            email_verified: boolean;
        };
        Session: {
            /** @description Short-lived JWT (HS256). Send as `Authorization: Bearer <token>`. */
            access_token: string;
            /** @description Opaque, single-use; rotates on every /auth/refresh call. */
            refresh_token: string;
            user: components["schemas"]["User"];
        };
        SessionEnvelope: {
            data: components["schemas"]["Session"];
            meta: Record<string, never>;
        };
        RefreshTokenRequest: {
            refresh_token: string;
        };
        RefreshedSession: {
            access_token: string;
            /** @description Replaces the one sent in the request — the old value stops working. */
            refresh_token: string;
        };
        RefreshEnvelope: {
            data: components["schemas"]["RefreshedSession"];
            meta: Record<string, never>;
        };
        LoggedOut: {
            /** @enum {boolean} */
            logged_out: true;
        };
        LoggedOutEnvelope: {
            data: components["schemas"]["LoggedOut"];
            meta: Record<string, never>;
        };
        PasswordForgotRequest: {
            /** Format: email */
            email: string;
        };
        Requested: {
            /** @enum {boolean} */
            requested: true;
        };
        RequestedEnvelope: {
            data: components["schemas"]["Requested"];
            meta: Record<string, never>;
        };
        PasswordResetRequest: {
            token: string;
            password: string;
        };
        Reset: {
            /** @enum {boolean} */
            reset: true;
        };
        ResetEnvelope: {
            data: components["schemas"]["Reset"];
            meta: Record<string, never>;
        };
        /** @enum {string} */
        Role: "user" | "moderator" | "admin" | "owner";
        AdminUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            email_verified_at: string | null;
            /** Format: date-time */
            blocked_at: string | null;
            /** Format: date-time */
            deleted_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdminUserEnvelope: {
            data: components["schemas"]["AdminUser"];
            meta: Record<string, never>;
        };
        PaginationMeta: {
            total: number;
            limit: number;
            offset: number;
        };
        AdminUserListEnvelope: {
            data: components["schemas"]["AdminUser"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        ChangeRoleRequest: {
            role: components["schemas"]["Role"];
        };
        Activated: {
            /** @enum {boolean} */
            activated: true;
        };
        ActivatedEnvelope: {
            data: components["schemas"]["Activated"];
            meta: Record<string, never>;
        };
        Blocked: {
            /** @enum {boolean} */
            blocked: true;
        };
        BlockedEnvelope: {
            data: components["schemas"]["Blocked"];
            meta: Record<string, never>;
        };
        Unblocked: {
            /** @enum {boolean} */
            unblocked: true;
        };
        UnblockedEnvelope: {
            data: components["schemas"]["Unblocked"];
            meta: Record<string, never>;
        };
        PasswordResetTriggered: {
            /** @enum {boolean} */
            password_reset_requested: true;
        };
        PasswordResetTriggeredEnvelope: {
            data: components["schemas"]["PasswordResetTriggered"];
            meta: Record<string, never>;
        };
    };
    responses: {
        /** @description Request body is not valid JSON, or contains an unknown field. */
        MalformedBody: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Request is well-formed JSON but fails a validation rule (email shape, password length). */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Too many requests from this client for this endpoint. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing, malformed, expired, or otherwise invalid access token. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated, but not permitted — not an admin, or a self-action such as demoting/blocking/deleting your own account. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No user exists with this id (or it has been soft-deleted). */
        UserNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description UUIDv7 of the target user. */
        UserIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service and database are both reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            /** @description Database is not reachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration accepted (whether or not the email was already taken). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterEnvelope"];
                };
            };
            400: components["responses"]["MalformedBody"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Email verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifiedEnvelope"];
                };
            };
            /** @description Token is malformed, or matches TokenInvalid: it never existed, has expired, or was already used. These are deliberately indistinguishable to the client — see security.md's user-enumeration guidance. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            400: components["responses"]["MalformedBody"];
            /** @description Invalid email or password. Returned identically whether the account exists or not — see security.md's user-enumeration guidance. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Credentials are correct but the email is not yet verified. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description New access/refresh pair issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshEnvelope"];
                };
            };
            400: components["responses"]["MalformedBody"];
            /** @description Refresh token is invalid, expired, or has been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Session revoked (or already was). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedOutEnvelope"];
                };
            };
            400: components["responses"]["MalformedBody"];
            429: components["responses"]["RateLimited"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordForgotRequest"];
            };
        };
        responses: {
            /** @description Request accepted (whether or not the account exists). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestedEnvelope"];
                };
            };
            400: components["responses"]["MalformedBody"];
            429: components["responses"]["RateLimited"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetEnvelope"];
                };
            };
            /** @description Token is malformed, expired, already used, or password is too short. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    listUsersAdmin: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of non-deleted users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getUserAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
    deleteUserAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account soft-deleted and anonymized (or already was). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
    activateUserAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account activated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivatedEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
    changeUserRoleAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleRequest"];
            };
        };
        responses: {
            /** @description The updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    triggerPasswordResetAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reset email requested. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetTriggeredEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
    blockUserAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account blocked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
    unblockUserAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account unblocked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnblockedEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
}
