/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database reachability check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account and email a verification token
         * @description If the email is already registered, this still returns 201 with a fresh id that resolves to nothing — the response cannot be used to tell whether an email is already taken. See decisions.md.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate an account with a verification token */
        post: operations["verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate and receive an access/refresh token pair */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token for a new access/refresh pair
         * @description Presenting a token that was already rotated or revoked fails this call and revokes every other token descended from the same login. See decisions.md.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the session a refresh token belongs to
         * @description Idempotent — an unknown or already-dead token is not an error.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/forgot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email a password-reset token if the account exists
         * @description Always returns the same response whether or not the email exists — see decisions.md.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set a new password given a valid reset token */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-deleted user accounts */
        get: operations["listUsersAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Typeahead search for users to attach as city managers
         * @description Purpose-built for the city-manager attach flow — always excludes blocked and deleted accounts and always filters by role, unlike GET /admin/users. Kept as a separate endpoint so that one's existing contract does not change under its existing callers. See decisions.md.
         */
        get: operations["searchManagerCandidatesAdmin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one user account, including a soft-deleted one */
        get: operations["getUserAdmin"];
        put?: never;
        post?: never;
        /**
         * Soft-delete and anonymize a user account
         * @description Anonymizes the row (email rewritten, password invalidated) and revokes every session the user holds. Idempotent — deleting an already-deleted account is still 204. An admin may not delete their own account. See decisions.md.
         */
        delete: operations["deleteUserAdmin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin override for the self-service email-verification gate
         * @description Lets the user use the app immediately, without going through /auth/verify-email. Idempotent. See decisions.md.
         */
        post: operations["activateUserAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change a user's role
         * @description An admin may not demote themselves away from admin — see decisions.md.
         */
        patch: operations["changeUserRoleAdmin"];
        trace?: never;
    };
    "/admin/users/{id}/password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Email the user a password-reset token
         * @description Reuses the exact same token-issuing flow as the self-service /auth/password/forgot, keyed by id instead of email. No plaintext password ever appears in this request or response — see decisions.md.
         */
        post: operations["triggerPasswordResetAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Block a user account
         * @description Revokes every session the user holds and rejects future logins with `account_blocked`. An admin may not block their own account. See decisions.md.
         */
        post: operations["blockUserAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unblock a user account */
        post: operations["unblockUserAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the cities the marketplace operates in */
        get: operations["listCitiesPublic"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/cities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-deleted cities (admin view — no manager lists, see decisions.md) */
        get: operations["listCitiesAdmin"];
        put?: never;
        /**
         * Create a city and auto-assign the creating admin as its manager
         * @description manager_ids is optional; each id must resolve to an existing, non-blocked, non-deleted user with role=manager, or the whole request fails with 422. The creating admin is always attached as a manager regardless of manager_ids. See decisions.md.
         */
        post: operations["createCityAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/cities/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one city, including a soft-deleted one */
        get: operations["getCityAdmin"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a city
         * @description Idempotent — deleting an already-deleted city is still 204.
         */
        delete: operations["deleteCityAdmin"];
        options?: never;
        head?: never;
        /**
         * Partially update a city's name, country_code, or centre point
         * @description lat and lon must be provided together or not at all. Managers are never changed through this endpoint — see POST/DELETE .../managers.
         */
        patch: operations["updateCityAdmin"];
        trace?: never;
    };
    "/admin/cities/{id}/managers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach a manager to a city
         * @description Idempotent — attaching an already-attached manager returns 200 unchanged. user_id must resolve to an existing, non-blocked, non-deleted user with role=manager.
         */
        post: operations["addCityManagerAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/cities/{id}/managers/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Detach a manager from a city
         * @description Idempotent — removing a user who was never attached is still 204.
         */
        delete: operations["removeCityManagerAdmin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the place-category catalog (cafe, bakery, ...)
         * @description Public, no auth. The catalog is seeded and read-only — there is no endpoint to create, rename, or reorder a category. See decisions.md M1-04.
         */
        get: operations["listPlaceCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List places, scoped to the actor's cities
         * @description role=admin sees every non-deleted place; role=manager sees only places whose city they manage. Categories and opening_hours are omitted from list items — see decisions.md M1-04 and patterns.md's list-vs-single-resource entry.
         */
        get: operations["listManagedPlaces"];
        put?: never;
        /**
         * Create a place, always status=pending
         * @description role=admin or role=manager. A manager may only create in a city they are attached to via city_managers — a manager of a different city gets 404 place_not_found, not 403: telling a manager "this exists, you just can't have it" would be an enumeration oracle. Every created place is status=pending regardless of who creates it; approve/reject are separate calls. See decisions.md M1-04.
         */
        post: operations["createManagedPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/places/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get one place, including a soft-deleted or non-approved one
         * @description Audit view, matching GetCityByID's convention — returns the place regardless of status or deleted_at, subject to the same city-scope check as every other /manage/places/* call.
         */
        get: operations["getManagedPlace"];
        put?: never;
        post?: never;
        /**
         * Soft-delete a place
         * @description Idempotent — deleting an already-deleted place is still 204.
         */
        delete: operations["deleteManagedPlace"];
        options?: never;
        head?: never;
        /**
         * Partially update a place
         * @description A nil/omitted field leaves the corresponding value unchanged. category_ids and opening_hours, when present (even as an empty array), fully replace the existing set. There is no city_id field — a place cannot change city, see decisions.md M1-04 #9; sending one is rejected as an unknown field (400 malformed_body).
         */
        patch: operations["updateManagedPlace"];
        trace?: never;
    };
    "/manage/places/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve a place
         * @description Idempotent and unconditional — any status may transition to approved, and repeating the call re-stamps reviewed_by/reviewed_at rather than erroring. See decisions.md M1-04 #7.
         */
        post: operations["approveManagedPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/manage/places/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a place with a required reason
         * @description Idempotent and unconditional, same as approve.
         */
        post: operations["rejectManagedPlace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /**
             * @description Stable machine-readable identifier. Switch on this, never on `message`.
             * @example validation_failed
             */
            code: string;
            /** @description Human-readable, may change without a version bump. */
            message: string;
            /** @description Present even when null. Structured extra context, e.g. field errors. */
            details: {
                [key: string]: unknown;
            } | null;
        };
        ErrorEnvelope: {
            error: components["schemas"]["Error"];
        };
        Health: {
            /** @enum {string} */
            status: "ok";
            /** @enum {string} */
            db: "ok";
        };
        HealthEnvelope: {
            data: components["schemas"]["Health"];
            meta: Record<string, never>;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        RegisteredUser: {
            /**
             * Format: uuid
             * @description UUIDv7. May not correspond to a real account — see decisions.md.
             */
            id: string;
            /** Format: email */
            email: string;
        };
        RegisterEnvelope: {
            data: components["schemas"]["RegisteredUser"];
            meta: Record<string, never>;
        };
        TokenRequest: {
            token: string;
        };
        Verified: {
            /** @enum {boolean} */
            verified: true;
        };
        VerifiedEnvelope: {
            data: components["schemas"]["Verified"];
            meta: Record<string, never>;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            email_verified: boolean;
        };
        Session: {
            /** @description Short-lived JWT (HS256). Send as `Authorization: Bearer <token>`. */
            access_token: string;
            /** @description Opaque, single-use; rotates on every /auth/refresh call. */
            refresh_token: string;
            user: components["schemas"]["User"];
        };
        SessionEnvelope: {
            data: components["schemas"]["Session"];
            meta: Record<string, never>;
        };
        RefreshTokenRequest: {
            refresh_token: string;
        };
        RefreshedSession: {
            access_token: string;
            /** @description Replaces the one sent in the request — the old value stops working. */
            refresh_token: string;
        };
        RefreshEnvelope: {
            data: components["schemas"]["RefreshedSession"];
            meta: Record<string, never>;
        };
        LoggedOut: {
            /** @enum {boolean} */
            logged_out: true;
        };
        LoggedOutEnvelope: {
            data: components["schemas"]["LoggedOut"];
            meta: Record<string, never>;
        };
        PasswordForgotRequest: {
            /** Format: email */
            email: string;
        };
        Requested: {
            /** @enum {boolean} */
            requested: true;
        };
        RequestedEnvelope: {
            data: components["schemas"]["Requested"];
            meta: Record<string, never>;
        };
        PasswordResetRequest: {
            token: string;
            password: string;
        };
        Reset: {
            /** @enum {boolean} */
            reset: true;
        };
        ResetEnvelope: {
            data: components["schemas"]["Reset"];
            meta: Record<string, never>;
        };
        /** @enum {string} */
        Role: "user" | "moderator" | "manager" | "admin" | "owner";
        AdminUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            role: components["schemas"]["Role"];
            /** Format: date-time */
            email_verified_at: string | null;
            /** Format: date-time */
            blocked_at: string | null;
            /** Format: date-time */
            deleted_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdminUserEnvelope: {
            data: components["schemas"]["AdminUser"];
            meta: Record<string, never>;
        };
        PaginationMeta: {
            total: number;
            limit: number;
            offset: number;
        };
        AdminUserListEnvelope: {
            data: components["schemas"]["AdminUser"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        ChangeRoleRequest: {
            role: components["schemas"]["Role"];
        };
        Activated: {
            /** @enum {boolean} */
            activated: true;
        };
        ActivatedEnvelope: {
            data: components["schemas"]["Activated"];
            meta: Record<string, never>;
        };
        Blocked: {
            /** @enum {boolean} */
            blocked: true;
        };
        BlockedEnvelope: {
            data: components["schemas"]["Blocked"];
            meta: Record<string, never>;
        };
        Unblocked: {
            /** @enum {boolean} */
            unblocked: true;
        };
        UnblockedEnvelope: {
            data: components["schemas"]["Unblocked"];
            meta: Record<string, never>;
        };
        PasswordResetTriggered: {
            /** @enum {boolean} */
            password_reset_requested: true;
        };
        PasswordResetTriggeredEnvelope: {
            data: components["schemas"]["PasswordResetTriggered"];
            meta: Record<string, never>;
        };
        /** @description The public shape — no managers, no deleted_at (soft-deleted cities never appear here). See decisions.md. */
        City: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** @description ISO 3166-1 alpha-2, e.g. BY. */
            country_code: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            /** Format: date-time */
            created_at: string;
        };
        CityListEnvelope: {
            data: components["schemas"]["City"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /** @description A denormalized city_managers row, joined with the user it points at. */
        CityManager: {
            /** Format: uuid */
            user_id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** Format: date-time */
            assigned_at: string;
        };
        /** @description The admin single-resource shape — create, get, and update all return this, with managers populated. See decisions.md. */
        AdminCity: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            country_code: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            managers: components["schemas"]["CityManager"][];
            /** Format: date-time */
            deleted_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdminCityEnvelope: {
            data: components["schemas"]["AdminCity"];
            meta: Record<string, never>;
        };
        /** @description Same columns as AdminCity, minus managers — joining city_managers at list scale is a different cost shape than this row's own columns. See decisions.md. */
        AdminCityListItem: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            country_code: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            /** Format: date-time */
            deleted_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        AdminCityListEnvelope: {
            data: components["schemas"]["AdminCityListItem"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreateCityRequest: {
            name: string;
            /** @description Supplied by the admin, not derived from name — city names here are frequently Cyrillic. See decisions.md. */
            slug: string;
            country_code: string;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            /** @description Optional. Each id must resolve to an existing, non-blocked, non-deleted user with role=manager. The creating admin is always attached in addition to these. */
            manager_ids?: string[];
        };
        /** @description A nil/omitted field leaves the corresponding column unchanged. */
        UpdateCityRequest: {
            name?: string;
            country_code?: string;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lon?: number;
        };
        AddManagerRequest: {
            /** Format: uuid */
            user_id: string;
        };
        /** @description One entry in the seeded, read-only place-category catalog. */
        PlaceCategory: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            sort_order: number;
        };
        PlaceCategoryListEnvelope: {
            data: components["schemas"]["PlaceCategory"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        /**
         * @description text + CHECK in the database, not a Postgres enum. See decisions.md M1-04
         * @enum {string}
         */
        PlaceStatus: "pending" | "approved" | "rejected";
        /** @description One weekday's opening interval. weekday is 1..7, 1=Monday, matching EXTRACT(ISODOW FROM ...) — see decisions.md M1-04 #16. opens_at/closes_at are venue-local wall-clock times, "HH:MM" through "24:00" inclusive — not UTC instants, see decisions.md M1-04 #14. No row for a weekday means closed that day; closes_at < opens_at means closing after midnight; opens_at="00:00" with closes_at="24:00" means open the full 24 hours, see decisions.md M1-04 #15. */
        OpeningHours: {
            weekday: number;
            opens_at: string;
            closes_at: string;
        };
        /** @description The staff single-resource shape — create, get, update, approve, and reject all return this, with categories and opening_hours populated. See patterns.md's list-vs-single-resource entry. */
        ManagedPlace: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            city_id: string;
            name: string;
            address: string | null;
            phone: string | null;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            status: components["schemas"]["PlaceStatus"];
            rejection_reason: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: uuid */
            reviewed_by: string | null;
            /** Format: date-time */
            reviewed_at: string | null;
            categories: components["schemas"]["PlaceCategory"][];
            opening_hours: components["schemas"]["OpeningHours"][];
            /** Format: date-time */
            deleted_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ManagedPlaceEnvelope: {
            data: components["schemas"]["ManagedPlace"];
            meta: Record<string, never>;
        };
        /** @description The staff list shape — same columns as ManagedPlace, minus categories and opening_hours. See patterns.md's list-vs-single-resource entry. */
        ManagedPlaceListItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            city_id: string;
            name: string;
            address: string | null;
            phone: string | null;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            status: components["schemas"]["PlaceStatus"];
            rejection_reason: string | null;
            /** Format: uuid */
            created_by: string;
            /** Format: uuid */
            reviewed_by: string | null;
            /** Format: date-time */
            reviewed_at: string | null;
            /** Format: date-time */
            deleted_at: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ManagedPlaceListEnvelope: {
            data: components["schemas"]["ManagedPlaceListItem"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        CreatePlaceRequest: {
            /** Format: uuid */
            city_id: string;
            name: string;
            address?: string | null;
            /** @description E.164 international format (e.g. "+375291234567"). Normalized server-side (spaces, hyphens, parens stripped) before validation. */
            phone?: string | null;
            /** Format: double */
            lat: number;
            /** Format: double */
            lon: number;
            category_ids?: string[];
            opening_hours?: components["schemas"]["OpeningHours"][];
        };
        /** @description A nil/omitted field leaves the corresponding value unchanged. category_ids and opening_hours, when present (even as an empty array), fully replace the existing set. No city_id field — see decisions.md M1-04 #9. */
        UpdatePlaceRequest: {
            name?: string;
            address?: string | null;
            phone?: string | null;
            /** Format: double */
            lat?: number;
            /** Format: double */
            lon?: number;
            category_ids?: string[];
            opening_hours?: components["schemas"]["OpeningHours"][];
        };
        RejectPlaceRequest: {
            reason: string;
        };
    };
    responses: {
        /** @description Request body is not valid JSON, or contains an unknown field. */
        MalformedBody: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Request is well-formed JSON but fails a validation rule (email shape, password length). */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Too many requests from this client for this endpoint. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Missing, malformed, expired, or otherwise invalid access token. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Authenticated, but not permitted — not an admin, or a self-action such as demoting/blocking/deleting your own account. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No user exists with this id (or it has been soft-deleted). */
        UserNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No city exists with this id. */
        CityNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description A non-deleted city already uses this slug. */
        SlugTaken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description No place exists with this id — or it does, but the actor is a manager not attached to its city. The two cases are deliberately indistinguishable; see decisions.md M1-04 #11. */
        PlaceNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        /** @description UUIDv7 of the target user. */
        UserIdPath: string;
        /** @description UUIDv7 of the target city. */
        CityIdPath: string;
        /** @description UUIDv7 of the manager being detached. */
        ManagerUserIdPath: string;
        /** @description UUIDv7 of the target place. */
        PlaceIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service and database are both reachable. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthEnvelope"];
                };
            };
            /** @description Database is not reachable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registration accepted (whether or not the email was already taken). */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterEnvelope"];
                };
            };
            400: components["responses"]["MalformedBody"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Email verified. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifiedEnvelope"];
                };
            };
            /** @description Token is malformed, or matches TokenInvalid: it never existed, has expired, or was already used. These are deliberately indistinguishable to the client — see security.md's user-enumeration guidance. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionEnvelope"];
                };
            };
            400: components["responses"]["MalformedBody"];
            /** @description Invalid email or password. Returned identically whether the account exists or not — see security.md's user-enumeration guidance. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Credentials are correct but the email is not yet verified. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description New access/refresh pair issued. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshEnvelope"];
                };
            };
            400: components["responses"]["MalformedBody"];
            /** @description Refresh token is invalid, expired, or has been revoked. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description Session revoked (or already was). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoggedOutEnvelope"];
                };
            };
            400: components["responses"]["MalformedBody"];
            429: components["responses"]["RateLimited"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordForgotRequest"];
            };
        };
        responses: {
            /** @description Request accepted (whether or not the account exists). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestedEnvelope"];
                };
            };
            400: components["responses"]["MalformedBody"];
            429: components["responses"]["RateLimited"];
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description Password changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetEnvelope"];
                };
            };
            /** @description Token is malformed, expired, already used, or password is too short. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["RateLimited"];
        };
    };
    listUsersAdmin: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of non-deleted users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    searchManagerCandidatesAdmin: {
        parameters: {
            query: {
                role: components["schemas"]["Role"];
                /** @description Case-insensitive substring match on email or display_name. */
                q?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of matching users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserListEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getUserAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
    deleteUserAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account soft-deleted and anonymized (or already was). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
    activateUserAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account activated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivatedEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
    changeUserRoleAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeRoleRequest"];
            };
        };
        responses: {
            /** @description The updated user. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    triggerPasswordResetAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reset email requested. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetTriggeredEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
    blockUserAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account blocked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockedEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
    unblockUserAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target user. */
                id: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account unblocked. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnblockedEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["UserNotFound"];
        };
    };
    listCitiesPublic: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of non-deleted cities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CityListEnvelope"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    listCitiesAdmin: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of non-deleted cities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCityListEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createCityAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCityRequest"];
            };
        };
        responses: {
            /** @description City created. */
            201: {
                headers: {
                    /** @description /v1/admin/cities/{id} of the new city. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCityEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["SlugTaken"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getCityAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target city. */
                id: components["parameters"]["CityIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The city, with its manager list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCityEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CityNotFound"];
        };
    };
    deleteCityAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target city. */
                id: components["parameters"]["CityIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description City soft-deleted (or already was). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CityNotFound"];
        };
    };
    updateCityAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target city. */
                id: components["parameters"]["CityIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCityRequest"];
            };
        };
        responses: {
            /** @description The updated city. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCityEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CityNotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    addCityManagerAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target city. */
                id: components["parameters"]["CityIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddManagerRequest"];
            };
        };
        responses: {
            /** @description The city, with the updated manager list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCityEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CityNotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    removeCityManagerAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target city. */
                id: components["parameters"]["CityIdPath"];
                /** @description UUIDv7 of the manager being detached. */
                userId: components["parameters"]["ManagerUserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manager detached (or already was). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["CityNotFound"];
        };
    };
    listPlaceCategories: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of categories, ordered by sort_order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceCategoryListEnvelope"];
                };
            };
            422: components["responses"]["ValidationFailed"];
        };
    };
    listManagedPlaces: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                city_id?: string;
                status?: components["schemas"]["PlaceStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of places this actor may manage. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedPlaceListEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    createManagedPlace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlaceRequest"];
            };
        };
        responses: {
            /** @description Place created, status=pending. */
            201: {
                headers: {
                    /** @description /v1/manage/places/{id} of the new place. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedPlaceEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PlaceNotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    getManagedPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target place. */
                id: components["parameters"]["PlaceIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The place. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedPlaceEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PlaceNotFound"];
        };
    };
    deleteManagedPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target place. */
                id: components["parameters"]["PlaceIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Place deleted (or already was). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PlaceNotFound"];
        };
    };
    updateManagedPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target place. */
                id: components["parameters"]["PlaceIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlaceRequest"];
            };
        };
        responses: {
            /** @description The updated place. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedPlaceEnvelope"];
                };
            };
            400: components["responses"]["MalformedBody"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PlaceNotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    approveManagedPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target place. */
                id: components["parameters"]["PlaceIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The approved place. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedPlaceEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PlaceNotFound"];
        };
    };
    rejectManagedPlace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUIDv7 of the target place. */
                id: components["parameters"]["PlaceIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RejectPlaceRequest"];
            };
        };
        responses: {
            /** @description The rejected place. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagedPlaceEnvelope"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["PlaceNotFound"];
            422: components["responses"]["ValidationFailed"];
        };
    };
}
